//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 DIP_System.rc 使用
//
#define IDR_MAINFRAME                   1
#define IDR_DIP_SYTYPE                  2
#define IDR_ACCELERATOR                 200
#define IDB_CHOOSE_CURVE                1001
#define IDB_CHOOSE_LINE                 1002
#define IDB_CURVEWND_INVERSE            1003
#define IDB_CURVEWND_RESET              1004
#define IDB_CURVE_CANCEL                1005
#define IDB_CURVE_OK                    1006
#define IDB_EXPORT_CURVE                1007
#define IDB_GROUP_BOX                   1008
#define IDB_IMPORT_CURVE                1009
#define IDC_ANGLE                       1010
#define IDC_BUTTON2                     1011
#define IDC_COMBO1                      1012
#define IDC_COMBOBOX_RGB                1013
#define IDC_COMBO_BPP                   1014
#define IDC_COORD                       1015
#define IDC_CURSOR                      1016
#define IDC_CVALUE                      1017
#define IDC_GAUSSIAN_MEAN               1018
#define IDC_GAUSSIAN_STD                1019
#define IDC_HISTOGRAM                   1020
#define IDC_ITEM1                       1021
#define IDC_ITEM2                       1022
#define IDC_LIMIT_LOWER                 1023
#define IDC_LIMIT_UP                    1024
#define IDC_MODE                        1025
#define IDC_NUM                         1026
#define IDC_PARAM                       1027
#define IDC_PARAMSET                    1028
#define IDC_POINTONE_X                  1029
#define IDC_POINTONE_Y                  1030
#define IDC_POINTTWO_X                  1031
#define IDC_POINTTWO_Y                  1032
#define IDC_PREV                        1033
#define IDC_SAVE                        1034
#define IDC_SET                         1035
#define IDC_SLIDER                      1036
#define IDC_SPIN                        1037
#define IDC_STATIC_BPP                  1038
#define IDC_STATIC_GRAY                 1039
#define IDC_STATIC_PER                  1040
#define IDC_VALUE                       1041
#define IDC_ZOOM_DLG_APPLY              1042
#define IDC_ZOOM_DLG_COMBO              1043
#define IDC_ZOOM_DLG_HEIGHT             1044
#define IDC_ZOOM_DLG_METHOD             1045
#define IDC_ZOOM_DLG_RATIO              1046
#define IDC_ZOOM_DLG_WIDTH              1047
#define IDD_ABOUTBOX                    1048
#define IDD_DLG_CHANGE_BPP              1049
#define IDD_DLG_COLORGRAD               1050
#define IDD_DLG_CURVE                   1051
#define IDD_DLG_DYNAMICCOMPRESS         1052
#define IDD_DLG_GAUSSIAN                1053
#define IDD_DLG_HISTOGRAM               1054
#define IDD_DLG_HIST_II                 1055
#define IDD_DLG_INTENSITY               1056
#define IDD_DLG_POINTDT                 1057
#define IDD_DLG_POINTDZ                 1058
#define IDD_DLG_POINTSTRE               1059
#define IDD_DLG_POINTWIN                1060
#define IDD_DLG_PREVIEW                 1061
#define IDD_DLG_ROTATE                  1062
#define IDD_DLG_ROTATE_II               1063
#define IDD_DLG_SETANGLE                1064
#define IDD_DLG_SETFREQ                 1065
#define IDD_DLG_SPACEFILTER             1066
#define IDD_DLG_STRETCH                 1067
#define IDD_DLG_THRESHOLD               1068
#define IDD_DLG_ZOOM                    1069
#define IDD_PREVIEW                     1070
#define IDD_WND_COLORGRAD               1071
#define IDD_WND_CURVE                   1072
#define IDD_WND_HISTOGRAM               1073
#define IDD_WND_SPACEFILTER             1074
#define IDE_CURVEWND_XPOSITION          1075
#define IDE_CURVEWND_YPOSITION          1076
#define IDI_COLORGRAD                   1077
#define IDI_CURVE                       1078
#define IDI_DIALOG                      1079
#define IDI_FILTER                      1080
#define IDI_FLIP_H                      1081
#define IDI_FLIP_V                      1082
#define IDI_HISTOGRAM                   1083
#define IDI_HIST_BLUE                   1084
#define IDI_HIST_GREEN                  1085
#define IDI_HIST_RED                    1086
#define IDI_REDO                        1090
#define IDI_ROTATE                      1091
#define IDI_THRESHOLD                   1092
#define IDI_TO_GRAY                     1093
#define IDI_TRANSPOSE                   1094
#define IDI_UNDO                        1095
#define IDI_ZOOMIN                      1096
#define IDI_ZOOMOUT                     1097
#define IDI_ZOOM_DEFAULT                1098
#define IDI_ZOOM_DLG                    1099
#define IDI_ZOOM_FIT_VIEW               1100
#define IDM_EMBOSS_1                    1101
#define IDM_EMBOSS_2                    1102
#define IDM_EMBOSS_3                    1103
#define IDM_EMBOSS_4                    1104
#define IDM_EMBOSS_5                    1105
#define IDM_EMBOSS_6                    1106
#define IDM_EMBOSS_7                    1107
#define IDM_EMBOSS_8                    1108
#define IDR_MYTOOLBAR                   1111
#define IDS_CURVEWND_XLABEL             1112
#define IDS_CURVEWND_YLABEL             1113
#define ID_AUTHOR_BLOG                  1133
#define ID_AUTHOR_MICRO_BLOG            1134
#define ID_BUTTERWORTH_H                1135
#define ID_BUTTERWORTH_L                1136
#define ID_CALL_BPP_DLG                 1137
#define ID_CALL_COLORGRAD_DLG           1138
#define ID_CALL_CURVE_DLG               1139
#define ID_CALL_HISTGRAM_DLG            1140
#define ID_CALL_HISTOGRAM_DLG           1141
#define ID_CALL_ROTATE_DLG              1142
#define ID_CALL_SPACEFILTER_DLG         1143
#define ID_CALL_STRETCH_DLG             1144
#define ID_CALL_THRESHOLD_DLG           1145
#define ID_CALL_ZOOM_DLG                1146
#define ID_CG_WND_COMBO                 1147
#define ID_CG_WND_EDIT_LEFTBOTTOM       1148
#define ID_CG_WND_EDIT_LEFTTOP          1149
#define ID_CG_WND_EDIT_RIGHTBOTTOM      1150
#define ID_CG_WND_EDIT_RIGHTTOP         1151
#define ID_CG_WND_EDIT_TOP              1152
#define ID_CG_WND_GROUP_UP              1153
#define ID_CG_WND_INPUT                 1154
#define ID_CG_WND_OUTPUT                1155
#define ID_CLOSE_OPERATE                1156
#define ID_CONTOURDIB                   1157
#define ID_CONVERT_RGB_2_BGR            1158
#define ID_CONVERT_RGB_2_BRG            1159
#define ID_CONVERT_RGB_2_GBR            1160
#define ID_CONVERT_RGB_2_GRB            1161
#define ID_CONVERT_RGB_2_RBG            1162
#define ID_CUDA_32922                   1163
#define ID_CUDA_SIMPLE_TEXTURE          1164
#define ID_CUTWAVE                      1165
#define ID_DWT                          1166
#define ID_DYNAMIC_COMPRESS             1167
#define ID_FILE_MYOPEN                  1168
#define ID_FILE_OPEN_PBM                1169
#define ID_FILE_OPEN_PGM                1170
#define ID_FILE_OPEN_PPM                1171
#define ID_FILE_REOPEN                  1172
#define ID_FLIP_HORIZONTAL              1173
#define ID_FLIP_VERTICAL                1174
#define ID_FREQ_DCT                     1175
#define ID_FREQ_FOUR                    1176
#define ID_FREQ_WALH                    1177
#define ID_G1_FILTER                    1178
#define ID_G2_FILTER                    1179
#define ID_G3_FILTER                    1180
#define ID_GEOM_ZOOMIN                  1181
#define ID_GEOM_ZOOMOUT                 1182
#define ID_GET_CURRENT_PIXEL            1183
#define ID_GET_WATERMARKING             1184
#define ID_GUASS__LAPLACIAN             1185
#define ID_HISTOGRAM_II                 1186
#define ID_HIST_WND_AHE                 1187
#define ID_HIST_WND_CLAHE               1188
#define ID_HIST_WND_HE                  1189
#define ID_HIST_WND_LHE                 1190
#define ID_HIST_WND_RESET               1191
#define ID_HORIZONTAL_FLAP              1192
#define ID_HORIZONTAL_FLIP              1193
#define ID_HOUGH                        1194
#define ID_HUFFMAN                      1195
#define ID_H_DILATION                   1196
#define ID_H_EROSION                    1197
#define ID_IDWT                         1198
#define ID_INTERACT                     1199
#define ID_INTERACT_BLACK               1200
#define ID_INTERACT_RED                 1201
#define ID_INTERACT_WHITE               1202
#define ID_ITERATE_THRESHOLD            1203
#define ID_JPEG_DECODING                1204
#define ID_JPEG_ENCODING                1205
#define ID_KRISCH                       1206
#define ID_LAPLACIAN                    1207
#define ID_LINE_QUICK_FILTER            1208
#define ID_LINE_SMOOTH_FILTER           1209
#define ID_LINE_SMOOTH_FILTER2          1210
#define ID_LINE_SMOOTH_FILTER3          1211
#define ID_LZW_DECODING                 1212
#define ID_LZW_ENCODING                 1213
#define ID_MAT                          1214
#define ID_MEDIAN_FILTER                1215
#define ID_MIN_POWER                    1216
#define ID_MUTUAL_FILTER                1217
#define ID_OPEN_OPERATE                 1218
#define ID_OVERRUN_FILTER               1219
#define ID_PCX_DECODING                 1220
#define ID_PCX_ENCODING                 1221
#define ID_POINT_DT                     1222
#define ID_POINT_DZ                     1223
#define ID_POINT_EQUA                   1224
#define ID_POINT_GML                    1225
#define ID_POINT_INVERT                 1226
#define ID_POINT_SML                    1227
#define ID_POINT_STRE                   1228
#define ID_POINT_WIND                   1229
#define ID_PREWITT                      1230
#define ID_PSE_FILTER                   1231
#define ID_RANDOM_NOISE                 1232
#define ID_RECTINICATION                1233
#define ID_RETRORSE_FILTER              1234
#define ID_RGN_GROW                     1235
#define ID_ROBERTS                      1236
#define ID_ROTATE                       1237
#define ID_SALT_NOISE                   1238
#define ID_SET_INTENSITY                1239
#define ID_SET_WATERMARKING             1240
#define ID_SF_WND_APPLY                 1241
#define ID_SF_WND_COMBO                 1242
#define ID_SF_WND_FILTER_SIZE           1243
#define ID_SF_WND_GAUSSIAN_NOISE        1244
#define ID_SF_WND_MEDIAN_FILTER         1245
#define ID_SF_WND_PEPPERSALT_NOISE      1246
#define ID_SF_WND_RESET                 1247
#define ID_SF_WND_SAMEDIAN_FILTER       1248
#define ID_SHANNON_FANNON               1249
#define ID_SOBEL                        1250
#define ID_TEMP_FILE                    1251
#define ID_THICK                        1252
#define ID_THIN                         1253
#define ID_TOGRAY                       1254
#define ID_TRACEDIB                     1255
#define ID_TRANSPOSE                    1256
#define ID_VERTICAL_FLAP                1257
#define ID_VERTICAL_FLIP                1258
#define ID_VH_DILATION                  1259
#define ID_VH_EROSION                   1260
#define ID_VIEW_ALL_CHANNEL_IMAGE       1261
#define ID_VIEW_B_CHANNEL_IMAGE         1262
#define ID_VIEW_B_INTENSITY             1263
#define ID_VIEW_DEFAULT                 1264
#define ID_VIEW_FIT_WINDOW              1265
#define ID_VIEW_G_CHANNEL_IMAGE         1266
#define ID_VIEW_G_INTENSITY             1267
#define ID_VIEW_INTENSITY               1268
#define ID_VIEW_R_CHANNEL_IMAGE         1269
#define ID_VIEW_R_INTENSITY             1270
#define ID_VIEW_SCREEN_SIZE             1271
#define ID_VIEW_ZOOMIN                  1272
#define ID_VIEW_ZOOMOUT                 1273
#define ID_V_DILATION                   1274
#define ID_V_EROSION                    1275
#define ID_WIENER_FILTER                1276
#define ID_32958                        32958
#define ID_HOTKEY_CTRL_N                32959
#define ID_HOTKEY_CTRL_O                32960
#define ID_HOTKEY_CTRL_W                32961
#define ID_HOTKEY_CTRL_S                32962
#define ID_HOTKEY_CTRL_Q                32963
#define ID_HOTKEY_CTRL_P                32964
#define ID_HOTKEY_CTRL_Z                32965
#define ID_HOTKEY_CTRL_R                32966
#define ID_HOTKEY_CTRL_C                32967
#define ID_HOTKEY_CTRL_V                32968
#define ID_HOTKEY_CTRL_0                32969
#define ID_HOTKEY_ZOOM_IN               32970
#define ID_HOTKEY_ZOOM_OUT              32971
#define ID_HOTKEY_CTRL_L                32972
#define ID_HOTKEY_CTRL_M                32973
#define ID_HOTKEY_CTRL_H                32974
#define ID_HOTKEY_CTRL_F                32975
#define ID_HOTKEY_ALT_Z                 32976
#define ID_32978                        32978

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32979
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
